---
- hosts: all
  remote_user: ayush
  tasks:
  - name: Change the sestatus from permissive to disable
    become: yes
    copy:
      src: /etc/selinux/config
      dest: /etc/selinux/config
  - name: Restart the servers
    become: yes
    reboot:
  - name: Stop thr firewalld
    service:
      name: firewalld
      state: stopped
    become: yes

