---
- name: Download latest tomcat file
  get_url:
    url:  "{{ abc }}"
    dest: "/opt/apache-tomcat-8.5.45.tar.gz"
    mode: '0644'
- name: Extract the tomcat tar file
  unarchive:
    src: "/opt/apache-tomcat-8.5.45.tar.gz"
    dest: "/opt/"
    remote_src: yes  
- name: Remane tomcat file
  command: mv -vn '/opt/apache-tomcat-8.5.45/' '/opt/tomcat/'
- name: Start the Tomcat Service
  shell: "nohup sh {{ TOMCAT_HOME }}/bin/catalina.sh start"
